services:
  backend:
    build:
      context: .
      dockerfile: /backend/Dockerfile
    env_file:
      - /backend/.env
    working_dir: /app/backend
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/challenge
  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: challenge
    ports:
      - "5432:5432"

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    working_dir: /app/frontend
    ports:
      - "80:80"
    depends_on:
      - backend
